#!/usr/bin/env python3
"""
Render L2 Reader JSON content to branded HTML + PDF
====================================================
Takes the JSON content files generated by create_l2_readers.py
and renders them as branded ModelIt! HTML, then converts to PDF.

Usage:
    python render_l2_reader_pdfs.py          # All L2 readers
    python render_l2_reader_pdfs.py --grade 06_L2  # One grade
"""

import os, sys, json, subprocess, argparse
from pathlib import Path

CHROME = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
BASE_DIR = Path.home() / "cast-science-resources" / "materials"

LEVEL_LABELS = {
    "advanced": "Advanced",
    "grade": "GradeLevel",
    "below": "BelowLevel",
    "esl": "ESL-Assisted",
}

LEVEL_COLORS = {
    "advanced": "#4A3A7A",
    "grade": "#6B5B95",
    "below": "#5BBFCF",
    "esl": "#F39C12",
}

CSS = """
@import url('https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800&family=Quicksand:wght@500;600;700&display=swap');
@page { size: letter; margin: 0.5in; }
@media print { body { margin: 0; padding: 0; } .page { page-break-after: always; } .page:last-child { page-break-after: avoid; } }
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: 'Nunito', sans-serif; color: #2D2A45; line-height: 1.6; font-size: 11pt; background: white; }
.header { background: linear-gradient(135deg, #4A3A7A 0%, #6B5B95 50%, #5BBFCF 100%); color: white; padding: 16px 24px; border-radius: 0 0 12px 12px; margin-bottom: 16px; display: flex; justify-content: space-between; align-items: center; }
.header-logo { font-family: 'Quicksand', sans-serif; font-weight: 700; font-size: 18pt; }
.header-level { background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 20px; font-size: 10pt; font-weight: 700; }
.header-meta { font-size: 9pt; opacity: 0.9; }
h1 { font-family: 'Quicksand', sans-serif; font-size: 18pt; color: #1E1B4B; margin: 14px 0 8px; font-weight: 700; }
h2 { font-family: 'Quicksand', sans-serif; font-size: 14pt; color: #4A3A7A; margin: 12px 0 6px; font-weight: 700; border-bottom: 2px solid #E8E0F0; padding-bottom: 4px; }
h3 { font-family: 'Quicksand', sans-serif; font-size: 12pt; color: #6B5B95; margin: 10px 0 4px; }
.story-text { font-size: 11pt; line-height: 1.7; margin-bottom: 12px; text-align: justify; }
.vocab-card { background: #F5F0FA; border-left: 4px solid #6B5B95; padding: 8px 12px; margin: 6px 0; border-radius: 0 6px 6px 0; }
.vocab-term { font-weight: 800; color: #4A3A7A; font-size: 11pt; }
.vocab-def { font-size: 10pt; color: #3E3A55; }
.vocab-sentence { font-size: 9.5pt; color: #6B6880; font-style: italic; margin-top: 2px; }
.discussion-card { background: #E0F5F8; border: 1.5px solid #5BBFCF; border-radius: 8px; padding: 10px 14px; margin: 6px 0; }
.discussion-prompt { font-weight: 700; color: #1E1B4B; font-size: 10.5pt; }
.discussion-frame { font-size: 9.5pt; color: #6B6880; margin-top: 3px; }
.reflection-box { background: #F5F0FA; border: 2px solid #B8A9D4; border-radius: 10px; padding: 12px 16px; margin: 10px 0; }
.reflection-label { font-weight: 700; color: #4A3A7A; font-size: 10pt; }
.reflection-line { border-bottom: 1.5px solid #B8A9D4; height: 24px; margin: 4px 0; }
.think-about { background: #FEF3E2; border-left: 4px solid #F39C12; padding: 6px 10px; margin: 8px 0; border-radius: 0 6px 6px 0; font-size: 10pt; color: #3E3A55; }
.word-bank { background: #E0F5F8; padding: 8px 14px; border-radius: 8px; margin: 8px 0; }
.word-bank-title { font-weight: 700; color: #5BBFCF; font-size: 10pt; }
.word-bank-words { font-size: 10pt; display: flex; flex-wrap: wrap; gap: 8px; margin-top: 4px; }
.word-bank-word { background: white; padding: 2px 8px; border-radius: 4px; border: 1px solid #5BBFCF; }
.cognate-sidebar { background: #F5F0FA; padding: 8px 12px; border-radius: 8px; margin: 8px 0; font-size: 9.5pt; }
.cognate-row { display: flex; gap: 12px; margin: 2px 0; }
.cognate-en { font-weight: 700; color: #4A3A7A; }
.cognate-es { color: #6B6880; }
.go-deeper { background: linear-gradient(135deg, #1E1B4B, #4A3A7A); color: white; padding: 10px 14px; border-radius: 8px; margin: 10px 0; font-size: 10pt; }
.go-deeper-title { font-weight: 700; color: #5BBFCF; font-size: 10pt; margin-bottom: 4px; }
.check-prompt { background: #E8E0F0; padding: 6px 10px; border-radius: 6px; margin: 6px 0; font-size: 10pt; }
.footer { text-align: center; font-size: 8pt; color: #6B6880; margin-top: 16px; padding-top: 8px; border-top: 1px solid #E8E0F0; }
"""


def render_reader_html(lesson_id, level_key, content, level_color):
    """Render reader content JSON to branded HTML string."""
    label = LEVEL_LABELS[level_key]
    story = content.get("story", {})
    vocabulary = content.get("vocabulary", [])
    discussion = content.get("discussion_cards", [])
    reflection = content.get("reflection_frames", {})

    # Story content
    story_title = story.get("title", "Reading Passage")
    story_text = story.get("text", "").replace("\n", "<br>")

    # Build vocabulary section
    vocab_html = ""
    for v in vocabulary[:6]:
        phonetic = f' <span style="color:#6B6880;font-size:9pt;">({v["phonetic"]})</span>' if v.get("phonetic") else ""
        cognate = f' <span style="color:#F39C12;font-size:9pt;">[Spanish: {v["cognate"]}]</span>' if v.get("cognate") else ""
        sentence = f'<div class="vocab-sentence">"{v["use_sentence"]}"</div>' if v.get("use_sentence") else ""
        vocab_html += f'''<div class="vocab-card">
            <span class="vocab-term">{v.get("term","")}{phonetic}{cognate}</span>
            <div class="vocab-def">{v.get("definition","")}</div>
            {sentence}
        </div>'''

    # Think About It prompts
    think_html = ""
    for t in story.get("think_abouts", []):
        think_html += f'<div class="think-about"><strong>Think About It:</strong> {t}</div>'

    # Check prompts (below level)
    check_html = ""
    for c in story.get("check_prompts", []):
        check_html += f'<div class="check-prompt"><strong>Check:</strong> {c}</div>'

    # Word bank (ESL)
    word_bank_html = ""
    words = story.get("word_bank", [])
    if words:
        word_items = "".join([f'<span class="word-bank-word">{w}</span>' for w in words])
        word_bank_html = f'<div class="word-bank"><div class="word-bank-title">Word Bank</div><div class="word-bank-words">{word_items}</div></div>'

    # Cognate sidebar (ESL)
    cognate_html = ""
    cognates = story.get("cognate_sidebar", [])
    if cognates:
        rows = "".join([f'<div class="cognate-row"><span class="cognate-en">{c.get("english","")}</span> <span class="cognate-es">= {c.get("spanish","")}</span></div>' for c in cognates])
        cognate_html = f'<div class="cognate-sidebar"><strong>Cognates (English / Spanish):</strong>{rows}</div>'

    # Go Deeper (advanced)
    go_deeper_html = ""
    gd = story.get("go_deeper")
    if gd:
        go_deeper_html = f'<div class="go-deeper"><div class="go-deeper-title">Go Deeper</div>{gd}</div>'

    # Margin definitions (below level)
    margin_html = ""
    for md in story.get("margin_defs", []):
        margin_html += f'<div class="vocab-card"><span class="vocab-term">{md.get("term","")}</span><div class="vocab-def">{md.get("definition","")}</div></div>'

    # Discussion cards
    disc_html = ""
    for d in discussion[:4]:
        frame = f'<div class="discussion-frame">Start with: "{d["frame"]}"</div>' if d.get("frame") else ""
        disc_html += f'<div class="discussion-card"><div class="discussion-prompt">{d.get("prompt","")}</div>{frame}</div>'

    # Reflection
    refl_html = '<div class="reflection-box">'
    for key, label_text in [("knew", "I already knew..."), ("learned", "I learned..."), ("wonder", "Now I wonder...")]:
        frame = reflection.get(key, "")
        refl_html += f'<div class="reflection-label">{label_text}</div>'
        if frame:
            refl_html += f'<div style="font-size:9.5pt;color:#6B6880;margin-bottom:2px;">{frame}</div>'
        refl_html += '<div class="reflection-line"></div>'
    refl_html += '</div>'

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{lesson_id} Reader - {label}</title>
<style>{CSS}</style>
</head>
<body>

<div class="header">
    <div>
        <div class="header-logo">ModelIt!</div>
        <div class="header-meta">{lesson_id} | Differentiated Reader</div>
    </div>
    <div class="header-level" style="background:{level_color};">{label}</div>
</div>

{word_bank_html}
{cognate_html}

<h1>{story_title}</h1>

<div class="story-text">{story_text}</div>

{think_html}
{check_html}
{margin_html}
{go_deeper_html}

<h2>Key Vocabulary</h2>
{vocab_html}

<h2>Discussion Questions</h2>
{disc_html}

<h2>Reflection</h2>
{refl_html}

<div class="footer">
    ModelIt! &mdash; Discovery Collective &copy; 2026 | {lesson_id} | {label} Reader
</div>

</body>
</html>"""
    return html


def convert_html_to_pdf(html_path, pdf_path):
    """Convert HTML to PDF via headless Chrome."""
    cmd = [
        CHROME, "--headless=new", "--disable-gpu", "--no-sandbox",
        "--disable-extensions", "--run-all-compositor-stages-before-draw",
        f"--print-to-pdf={pdf_path}", "--print-to-pdf-no-header",
        html_path.as_uri(),
    ]
    try:
        subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        return Path(pdf_path).exists() and Path(pdf_path).stat().st_size > 0
    except:
        return False


def process_all(grade_filter=None):
    """Process all L2 reader content files to PDF."""
    grades = ["04", "05", "06", "07", "08"]
    if grade_filter:
        grades = [grade_filter.split("_")[0]]

    total = 0
    success = 0

    for g in grades:
        level2_dir = BASE_DIR / f"grade-{g}" / "level-2"
        if not level2_dir.exists():
            continue

        for lesson_dir in sorted(level2_dir.iterdir()):
            if not lesson_dir.is_dir():
                continue
            readers_dir = lesson_dir / "readers"
            if not readers_dir.exists():
                continue

            lesson_id = lesson_dir.name  # e.g., G04L2-L01

            for level_key, label in LEVEL_LABELS.items():
                content_file = readers_dir / f"content-{level_key}.json"
                if not content_file.exists():
                    continue

                pdf_file = lesson_dir / f"{lesson_id}-Reader-{label}.pdf"
                if pdf_file.exists() and pdf_file.stat().st_size > 0:
                    total += 1
                    success += 1
                    continue

                total += 1

                # Load content
                with open(content_file, "r", encoding="utf-8") as f:
                    content = json.load(f)

                # Render HTML
                color = LEVEL_COLORS.get(level_key, "#6B5B95")
                html_str = render_reader_html(lesson_id, level_key, content, color)

                html_file = lesson_dir / f"_temp_reader_{level_key}.html"
                with open(html_file, "w", encoding="utf-8") as f:
                    f.write(html_str)

                # Convert to PDF
                ok = convert_html_to_pdf(html_file, pdf_file)
                html_file.unlink(missing_ok=True)

                if ok:
                    success += 1
                    size_kb = pdf_file.stat().st_size // 1024
                    print(f"  [OK] {pdf_file.name} ({size_kb}KB)")
                else:
                    print(f"  [FAIL] {pdf_file.name}")

    print(f"\nDone: {success}/{total} PDFs generated")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--grade", help="e.g., 04_L2")
    args = parser.parse_args()
    process_all(args.grade)
